export type Provider = {
  id: string;
  name: string;
  slug: string;
  organizationSlug: string;
  locationSlug: string;
  organizationLocationCount: number;
  description: string | null;
  address: string | null;
  city: string;
  state: string;
  postalCode: string | null;
  latitude: number | null;
  longitude: number | null;
  phone: string | null;
  website: string | null;
  categories: string[];
  levelsOfCare: string[];
  insurance: string[];
  insuranceDetails: string | null;
  treatmentTypes: string[];
  therapies: string[];
  amenities: string[];
  specialties: string[];
  featuredImageUrl: string | null;
  imageUrls: string[];
  priceRange: string | null;
  treatmentDuration: string | null;
  sourceRatingValue: number | null;
  sourceRatingCount: number | null;
  evidenceScore: number;
  licenseSummary: string | null;
  accreditation: string[];
  sourceUrl: string | null;
  lastVerifiedAt: string | null;
  updatedAt: string;
  verificationStatus: "listed" | "data-verified" | "provider-confirmed" | "independently-reviewed";
  isSponsored: boolean;
};
