export type Provider = {
  id: string;
  name: string;
  slug: string;
  organizationSlug: string;
  locationSlug: string;
  organizationLocationCount: number;
  description: string | null;
  address: string | null;
  city: string;
  state: string;
  postalCode: string | null;
  latitude: number | null;
  longitude: number | null;
  phone: string | null;
  website: string | null;
  categories: string[];
  levelsOfCare: string[];
  insurance: string[];
  insuranceDetails: string | null;
  treatmentTypes: string[];
  therapies: string[];
  amenities: string[];
  specialties: string[];
  featuredImageUrl: string | null;
  imageUrls: string[];
  priceRange: string | null;
  treatmentDuration: string | null;
  sourceRatingValue: number | null;
  sourceRatingCount: number | null;
  publicReviewRatingValue: number | null;
  publicReviewRatingCount: number | null;
  publicReviewSourceName: string | null;
  evidenceScore: number;
  licenseSummary: string | null;
  accreditation: string[];
  sourceUrl: string | null;
  lastVerifiedAt: string | null;
  updatedAt: string;
  verificationStatus: "listed" | "data-verified" | "provider-confirmed" | "independently-reviewed";
  isSponsored: boolean;
};

export type ReviewTheme = {
  label: string;
  reviewCount: number;
};

export type ReviewSignal = {
  sourceType: "google" | "recovery.com" | "rehab.com" | "rehabs.com" | "other";
  sourceName: string;
  sourceUrl: string;
  externalPlaceId: string | null;
  averageRating: number | null;
  reviewCount: number | null;
  sampledReviewCount: number;
  textReviewCount: number;
  ratingDistribution: Record<string, number>;
  reviewSummary: string | null;
  positiveThemes: ReviewTheme[];
  concernThemes: ReviewTheme[];
  summaryLimitations: string | null;
  reviewDateStart: string | null;
  reviewDateEnd: string | null;
  matchConfidence: number | null;
  sourceNotes: string | null;
  collectionMethod: string;
  fetchedAt: string;
};

export type ProviderProfileDetails = {
  email: string | null;
  intakePhone: string | null;
  officialWebsite: string | null;
  operatingDays: string[];
  is24Hours: boolean | null;
  evidenceSourceCount: number | null;
  evidenceSources: string[];
  supportServices: string[];
  accessServices: string[];
  coordinatedServices: string[];
  medicationServices: string[];
  languages: string[];
};
