/**
 * RecoveryOn Directory - Shared Data Model
 * Exposes categories, states, and demo resources.
 */

window.RECOVERY_CATEGORIES = [
    { name: "Treatment Centers", icon: "fa-house-medical", slug: "treatment-centers", countText: "0 centers" },
    { name: "Counseling & Therapy", icon: "fa-user-doctor", slug: "counseling-therapy", countText: "0 therapists" },
    { name: "Detox Programs", icon: "fa-droplet", slug: "detox-programs", countText: "0 programs" },
    { name: "Support Groups", icon: "fa-users", slug: "support-groups", countText: "0 groups" },
    { name: "Sober Living", icon: "fa-bed", slug: "sober-living", countText: "0 homes" },
    { name: "Mental Health Services", icon: "fa-brain", slug: "mental-health", countText: "0 services" },
    { name: "Outpatient Treatment", icon: "fa-door-open", slug: "outpatient", countText: "0 clinics" },
    { name: "Holistic Wellness", icon: "fa-leaf", slug: "holistic-wellness", countText: "0 centers" }
];

window.RECOVERY_STATES = [
    { name: "Alabama", abbr: "AL", count: 0 }, { name: "Alaska", abbr: "AK", count: 0 }, { name: "Arizona", abbr: "AZ", count: 0 },
    { name: "Arkansas", abbr: "AR", count: 0 }, { name: "California", abbr: "CA", count: 0 }, { name: "Colorado", abbr: "CO", count: 0 },
    { name: "Connecticut", abbr: "CT", count: 0 }, { name: "Delaware", abbr: "DE", count: 0 }, { name: "District of Columbia", abbr: "DC", count: 0 },
    { name: "Florida", abbr: "FL", count: 0 }, { name: "Georgia", abbr: "GA", count: 0 }, { name: "Hawaii", abbr: "HI", count: 0 },
    { name: "Idaho", abbr: "ID", count: 0 }, { name: "Illinois", abbr: "IL", count: 0 }, { name: "Indiana", abbr: "IN", count: 0 },
    { name: "Iowa", abbr: "IA", count: 0 }, { name: "Kansas", abbr: "KS", count: 0 }, { name: "Kentucky", abbr: "KY", count: 0 },
    { name: "Louisiana", abbr: "LA", count: 0 }, { name: "Maine", abbr: "ME", count: 0 }, { name: "Maryland", abbr: "MD", count: 0 },
    { name: "Massachusetts", abbr: "MA", count: 0 }, { name: "Michigan", abbr: "MI", count: 0 }, { name: "Minnesota", abbr: "MN", count: 0 },
    { name: "Mississippi", abbr: "MS", count: 0 }, { name: "Missouri", abbr: "MO", count: 0 }, { name: "Montana", abbr: "MT", count: 0 },
    { name: "Nebraska", abbr: "NE", count: 0 }, { name: "Nevada", abbr: "NV", count: 0 }, { name: "New Hampshire", abbr: "NH", count: 0 },
    { name: "New Jersey", abbr: "NJ", count: 0 }, { name: "New Mexico", abbr: "NM", count: 0 }, { name: "New York", abbr: "NY", count: 0 },
    { name: "North Carolina", abbr: "NC", count: 0 }, { name: "North Dakota", abbr: "ND", count: 0 }, { name: "Ohio", abbr: "OH", count: 0 },
    { name: "Oklahoma", abbr: "OK", count: 0 }, { name: "Oregon", abbr: "OR", count: 0 }, { name: "Pennsylvania", abbr: "PA", count: 0 },
    { name: "Rhode Island", abbr: "RI", count: 0 }, { name: "South Carolina", abbr: "SC", count: 0 }, { name: "South Dakota", abbr: "SD", count: 0 },
    { name: "Tennessee", abbr: "TN", count: 0 }, { name: "Texas", abbr: "TX", count: 0 }, { name: "Utah", abbr: "UT", count: 0 },
    { name: "Vermont", abbr: "VT", count: 0 }, { name: "Virginia", abbr: "VA", count: 0 }, { name: "Washington", abbr: "WA", count: 0 },
    { name: "West Virginia", abbr: "WV", count: 0 }, { name: "Wisconsin", abbr: "WI", count: 0 }, { name: "Wyoming", abbr: "WY", count: 0 }
];

window.RECOVERY_RESOURCES = [
    {
        name: "Serene Path Wellness Center",
        slug: "serene-path-wellness",
        category: "Holistic Clinic",
        image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80",
        statusText: "Verified Center",
        state: "CO",
        county: "Boulder County",
        city: "Boulder",
        area: "Front Range",
        address: "123 Serene Way, Boulder, CO 80301",
        latitude: 40.0150,
        longitude: -105.2705,
        categories: ["Holistic Wellness", "Counseling & Therapy"],
        treatmentTypes: ["Acupuncture", "Yoga Therapy", "Meditation", "Sound Healing"],
        rating: 4.9,
        reviewCount: 34,
        insuranceAccepted: ["Blue Cross Blue Shield", "Aetna", "UnitedHealthcare"],
        logo: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=150&h=150&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1599447421416-3414500d18a5?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80"
        ],
        phone: "+1 (303) 555-0199",
        email: "contact@serenepath.org",
        website: "https://example.com/serene-path",
        aboutShort: "A holistic clinic offering yoga, sound healing, and acupuncture in Boulder.",
        aboutLong: "Serene Path Wellness Center provides a calm, supportive environment where individuals can engage in alternative recovery therapies. Our clinic features certified instructors and clinical practitioners who specialize in integrating physical movement with emotional healing. All services listed for this facility are part of a demonstration dataset for testing layout components.",
        services: ["Sound baths", "Group meditation", "Acupuncture", "Private yoga classes"],
        amenities: ["Outdoor Zen garden", "Herbal tea station", "Private therapy rooms"],
        status: "Demo Data / Testing Only"
    },
    {
        name: "Hope & Unity Fellowship",
        slug: "hope-unity-fellowship",
        category: "Support Group",
        image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=600&q=80",
        statusText: "Free Consultations",
        state: "TX",
        county: "Travis County",
        city: "Austin",
        area: "Downtown Austin",
        address: "704 Congress Ave, Austin, TX 78701",
        latitude: 30.2701,
        longitude: -97.7418,
        categories: ["Support Groups"],
        treatmentTypes: ["12-Step Groups", "Peer Support", "Family Counseling"],
        rating: 4.8,
        reviewCount: 19,
        insuranceAccepted: [],
        logo: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=150&h=150&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1521791136368-1a983b75a907?auto=format&fit=crop&w=600&q=80"
        ],
        phone: "+1 (512) 555-0144",
        email: "info@hopeandunity.org",
        website: "https://example.com/hope-unity",
        aboutShort: "A supportive peer recovery group providing group discussions and meetings in Austin.",
        aboutLong: "Hope & Unity Fellowship is dedicated to providing community-driven support for individuals recovering from substance use disorders. We host weekly peer group discussions, family sessions, and sober socials. All listed details are sample data for layout design validation.",
        services: ["12-Step facilitation", "Weekly support circles", "Sober social gatherings", "Family education programs"],
        amenities: ["Spacious meeting hall", "Coffee bar", "Children play room"],
        status: "Demo Data / Testing Only"
    },
    {
        name: "Apex Therapy Associates",
        slug: "apex-therapy-associates",
        category: "Counseling",
        image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=600&q=80",
        statusText: "Insurance Accepted",
        state: "NY",
        county: "New York County",
        city: "New York",
        area: "Manhattan",
        address: "350 Fifth Ave, New York, NY 10118",
        latitude: 40.7484,
        longitude: -73.9857,
        categories: ["Counseling & Therapy"],
        treatmentTypes: ["CBT", "DBT", "Individual Therapy", "Psychotherapy"],
        rating: 5.0,
        reviewCount: 42,
        insuranceAccepted: ["Aetna", "Cigna", "Empire Blue Cross"],
        logo: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=150&h=150&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1527689368864-3a821dbccc34?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=80"
        ],
        phone: "+1 (212) 555-0178",
        email: "appointments@apextherapy.net",
        website: "https://example.com/apex-therapy",
        aboutShort: "Professional counseling and psychotherapy clinic based in Manhattan.",
        aboutLong: "Apex Therapy Associates offers evidence-based cognitive behavioral therapy (CBT) and dialectical behavior therapy (DBT) sessions. Our certified therapists specialize in trauma, anxiety, and addiction recovery, helping clients build sustainable coping mechanisms. All elements shown represent mock layout structures.",
        services: ["Cognitive Behavioral Therapy", "Psychodynamic Therapy", "Trauma-Informed Counseling", "Stress Management"],
        amenities: ["Quiet consultation suites", "Virtual telehealth option", "ADA accessible offices"],
        status: "Demo Data / Testing Only"
    },
    {
        name: "Elysian Recovery Spa & Retreat",
        slug: "elysian-recovery-retreat",
        category: "Treatment Center",
        image: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=600&q=80",
        statusText: "Starting at $150/day",
        state: "CA",
        county: "San Diego County",
        city: "San Diego",
        area: "La Jolla",
        address: "7922 La Jolla Shores Dr, La Jolla, CA 92037",
        latitude: 32.8532,
        longitude: -117.2558,
        categories: ["Treatment Centers", "Holistic Wellness"],
        treatmentTypes: ["Residential Treatment", "Inpatient Rehab", "Medication Management"],
        rating: 4.7,
        reviewCount: 28,
        insuranceAccepted: ["Anthem Blue Cross", "Cigna", "Aetna", "Humana"],
        logo: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=150&h=150&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=600&q=80"
        ],
        phone: "+1 (858) 555-0150",
        email: "admissions@elysianretreat.com",
        website: "https://example.com/elysian-retreat",
        aboutShort: "A luxurious residential rehabilitation and wellness retreat in La Jolla.",
        aboutLong: "Elysian Recovery Spa & Retreat provides premium residential recovery programs combining clinical care with wellness therapies. Clients receive personalized recovery plans, gourmet meals, and access to therapeutic massage and spa amenities. All information listed is placeholder data for developer validation.",
        services: ["Medical detoxification", "Individual psychotherapy", "Family recovery workshops", "Relapse prevention training"],
        amenities: ["Oceanview rooms", "Full-service spa & pool", "Private chef & organic dining", "Fitness studio"],
        status: "Demo Data / Testing Only"
    },
    {
        name: "North Star Counseling Group",
        slug: "north-star-counseling",
        category: "Counseling",
        image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=600&q=80",
        statusText: "Verified Center",
        state: "WA",
        county: "King County",
        city: "Seattle",
        area: "Capitol Hill",
        address: "1521 11th Ave, Seattle, WA 98122",
        latitude: 47.6152,
        longitude: -122.3183,
        categories: ["Counseling & Therapy"],
        treatmentTypes: ["Outpatient Therapy", "Family Counseling", "Youth Programs"],
        rating: 4.9,
        reviewCount: 15,
        insuranceAccepted: ["Premera Blue Cross", "Regence BlueShield", "Aetna"],
        logo: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=150&h=150&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=600&q=80"
        ],
        phone: "+1 (206) 555-0131",
        email: "contact@northstarseattle.com",
        website: "https://example.com/north-star",
        aboutShort: "Certified mental health and addiction counseling located in Seattle.",
        aboutLong: "North Star Counseling Group is dedicated to helping Seattle residents overcome psychological challenges, anxiety, and chemical dependencies. We offer custom sessions for individuals, couples, and adolescents. All elements are structured mock samples.",
        services: ["Teen & adolescent therapy", "Couples counseling", "Addiction coping skills", "Grief and loss support"],
        amenities: ["Comfortable lounge area", "Online therapy portal", "Flexible evening scheduling"],
        status: "Demo Data / Testing Only"
    },
    {
        name: "Cascade Recovery Clinic",
        slug: "cascade-recovery-clinic",
        category: "Treatment Center",
        image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=600&q=80",
        statusText: "Insurance Accepted",
        state: "OR",
        county: "Multnomah County",
        city: "Portland",
        area: "Pearl District",
        address: "930 NW 14th Ave, Portland, OR 97209",
        latitude: 45.5298,
        longitude: -122.6853,
        categories: ["Treatment Centers", "Outpatient Treatment"],
        treatmentTypes: ["Intensive Outpatient Program (IOP)", "Sober Living Support", "Relapse Prevention"],
        rating: 4.6,
        reviewCount: 22,
        insuranceAccepted: ["Providence Health Plan", "Moda Health", "Kaiser Permanente"],
        logo: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=150&h=150&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80"
        ],
        phone: "+1 (503) 555-0142",
        email: "admissions@cascaderecovery.org",
        website: "https://example.com/cascade-recovery",
        aboutShort: "Intensive outpatient recovery program located in Portland's Pearl District.",
        aboutLong: "Cascade Recovery Clinic offers structured intensive outpatient programs (IOP) that allow clients to maintain their daily routines while receiving top-tier support. Our team emphasizes relational health and relapse prevention skills. All data displayed is mock content for interface design evaluation.",
        services: ["Intensive outpatient groups", "Sober companion coordination", "Medicated-assisted treatment consulting", "Nutrition and wellness guidance"],
        amenities: ["Modern facilities", "Transit-accessible location", "Sober lounge area"],
        status: "Demo Data / Testing Only"
    }
];
